.\" $Id$
.TH NDL-CHECK 1 2007-04-01 "" "Nodelist Tools"
.SH NAME
ndl-check \- Fidonet(tm) nodelist checker
.SH SYNOPSIS
.B ndl-check
[\fIFILE\fR]
.br
.SH DESCRIPTION
.PP
Checks a Fidonet nodediff or nodelist for proper formatting, line endings
and end of file ending. It displays the type of file detected and if the
file is a nodelist it does some additional checks on the data fields.
A summary of nodes, nets etc. is displayed after all checks are passed.
.SH AUTHOR
Written by Michiel Broek.
.SH REPORTING BUGS
Report bugs to <mbse@mbse.eu>
.SH SEE ALSO
notyet(1)
